require "user.functions"
--require "user.catppuccin"
require "user.colorscheme"
require "user.window_management"
require "user.settings"
require "user.autocommands"
require "user.chezmoi"
require "user.keymaps"
require "user.icons"

require "plugins"
