-- Autocommand that reloads neovim whenever you save the plugins.lua file
-- vim.cmd [[
--   augroup packer_user_config
--     autocmd!
--     autocmd BufWritePost plugins/init.lua source <afile> | PackerSync
--   augroup end
-- ]]

-- TODO: clear command line
-- function! s:empty_message(timer)
--     echo ''
-- endfunction
--
-- augroup cmdline
--     autocmd!
--     autocmd CmdlineLeave : call timer_start(5000, funcref('s:empty_message'))
-- augroup END
